name: tripoo
description: A home listing and properties app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 0.6.9
  firebase_core: ^0.7.0
  # Newly reworked plugins covered by this migration guide:
  firebase_auth: "^0.20.0+1"
  firebase_crashlytics: "^0.4.0+1"
  cloud_firestore: "^0.16.0"
  firebase_storage: "^7.0.0"
  firebase_messaging: "^8.0.0-dev.14"
  firebase_analytics: "^7.0.1"
  google_sign_in: ^4.5.9
  multi_image_picker: ^4.6.5
  flutter_bloc: ^6.0.0
  fzregex: ^1.0.3
  path_provider: ^1.6.27
  image_picker: ^0.6.7+22
  bloc: ^6.0.0
  injectable: ^1.0.7
  animated_text_kit: ^3.1.0
  google_maps_place_picker: ^1.0.1
  smart_select: ^4.3.2
  wiredash: ^0.4.0
  lottie: ^0.7.0+1
  custom_radio_grouped_button: ^1.0.6+1
  flushbar: ^1.10.4
  geolocator: ^6.1.13
  google_maps_flutter: ^1.0.6
  freezed_annotation:
  carousel_slider: ^3.0.0
  auto_animated: ^2.1.0
  cool_stepper: ^1.1.3
  kt_dart: ^0.8.0
  animations: ^1.1.2
  flutter_hooks: ^0.15.0
  toggle_switch: ^0.1.8
  skeleton_text: ^1.0.0
  dartz: ^0.9.2
  provider: 4.3.2+3
  flutter_slidable:
  md2_tab_indicator: ^1.0.2
  intl: ^0.16.1
  groovin_widgets: ^1.6.1
  flutter_range_slider: ^1.5.0
  supercharged: ^1.12.0
  like_button: ^1.0.4
  badges: ^1.1.6
  syncfusion_flutter_calendar: ^18.4.43
  cached_network_image:
  flutter_spinkit: ^4.1.2+1
  eva_icons_flutter: ^2.0.1
  datetime_picker_formfield: ^1.0.0
  get_it: ^5.0.3
  number_slide_animation: ^0.1.1
  validators: ^2.0.0
  grouped_list: ^3.7.1
  fl_chart: ^0.12.3

dev_dependencies:
  freezed: ^0.12.6
  json_serializable: ^3.3.0
  lint: ^1.0.0
  auto_route_generator: 0.6.10
  injectable_generator: ^1.0.7
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/util/



  fonts:
     - family: ProductSans
       fonts:
         - asset: fonts/Product-Sans-Bold.ttf
           weight: 800
         - asset: fonts/Product-Sans-Regular.ttf
     - family: Lato
       fonts:
         - asset: fonts/Lato-Regular.ttf
         - asset: fonts/Lato-Bold.ttf
           weight: 800
